[project]
name = "uma-emulator"
authors = ["UMA Development Team <dev@uma.xyz>"]
description = "Verification and certification platform for decentralized smart contracts"
telemetry = false
requirements = []
[contracts.uma-verification]
path = "contracts/uma-verification.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
